In [1]:
import pandas as pd
import numpy as np

In [4]:
results = pd.read_csv('results.csv')

In [12]:
results = results[results['tournament']!='Friendly']
results['date'] = pd.to_datetime(results['date'])

In [13]:
results.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22569 entries, 29 to 39022
Data columns (total 9 columns):
date          22569 non-null datetime64[ns]
home_team     22569 non-null object
away_team     22569 non-null object
home_score    22569 non-null int64
away_score    22569 non-null int64
tournament    22569 non-null object
city          22569 non-null object
country       22569 non-null object
neutral       22569 non-null bool
dtypes: bool(1), datetime64[ns](1), int64(2), object(5)
memory usage: 1.1+ MB

In [15]:
world_cup = pd.read_csv('World Cup 2018 Dataset.csv')
world_cup = world_cup.replace({"IRAN": "Iran", 
                               "Costarica": "Costa Rica", 
                               "Porugal": "Portugal", 
                               "Columbia": "Colombia", 
                               "Korea" : "Korea Republic"})
world_cup = world_cup.loc[:, ['Team', 'Group', 'First match \nagainst', 'Second match\n against', 'Third match\n against']]
world_cup.dropna(inplace=True)

world_cup = world_cup.set_index('Team')

In [17]:
results

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
29,1884-01-26,Northern Ireland,Scotland,0,5,British Championship,Belfast,Ireland,False
30,1884-02-09,Wales,Northern Ireland,6,0,British Championship,Wrexham,Wales,False
31,1884-02-23,Northern Ireland,England,1,8,British Championship,Belfast,Ireland,False
32,1884-03-15,Scotland,England,1,0,British Championship,Glasgow,Scotland,False
33,1884-03-17,Wales,England,0,4,British Championship,Wrexham,Wales,False
34,1884-03-29,Scotland,Wales,4,1,British Championship,Glasgow,Scotland,False
35,1885-02-28,England,Northern Ireland,4,0,British Championship,Manchester,England,False
36,1885-03-14,England,Wales,1,1,British Championship,Blackburn,England,False
37,1885-03-14,Scotland,Northern Ireland,8,2,British Championship,Glasgow,Scotland,False
38,1885-03-21,England,Scotland,1,1,British Championship,London,England,False
39,1885-03-23,Wales,Scotland,1,8,British Championship,Wrexham,Wales,False
40,1885-04-11,Northern Ireland,Wales,2,8,British Championship,Belfast,Ireland,False
42,1886-02-27,Wales,Northern Ireland,5,0,British Championship,Wrexham,Wales,False
43,1886-03-13,Northern Ireland,England,1,6,British Championship,Belfast,Ireland,False
44,1886-03-20,Northern Ireland,Scotland,2,7,British Championship,Belfast,Ireland,False
45,1886-03-27,Scotland,England,1,1,British Championship,Glasgow,Scotland,False
46,1886-03-29,Wales,England,1,3,British Championship,Wrexham,Wales,False
47,1886-04-10,Scotland,Wales,4,1,British Championship,Glasgow,Scotland,False
49,1887-02-05,England,Northern Ireland,7,0,British Championship,Sheffield,England,False
50,1887-02-19,Scotland,Northern Ireland,4,1,British Championship,Glasgow,Scotland,False
51,1887-02-26,England,Wales,4,0,British Championship,London,England,False
52,1887-03-12,Northern Ireland,Wales,4,1,British Championship,Belfast,Ireland,False
53,1887-03-19,England,Scotland,2,3,British Championship,Blackburn,England,False
54,1887-03-21,Wales,Scotland,0,2,British Championship,Wrexham,Wales,False
55,1888-02-04,England,Wales,5,1,British Championship,Crewe,England,False
56,1888-03-03,Wales,Northern Ireland,11,0,British Championship,Wrexham,Wales,False
57,1888-03-10,Scotland,Wales,5,1,British Championship,Edinburgh,Scotland,False
58,1888-03-17,Scotland,England,0,5,British Championship,Glasgow,Scotland,False
59,1888-03-24,Northern Ireland,Scotland,2,10,British Championship,Belfast,Ireland,False
60,1888-04-07,Northern Ireland,England,1,5,British Championship,Belfast,Ireland,False
...,...,...,...,...,...,...,...,...,...
38888,2018-03-27,Korea DPR,Hong Kong,2,0,AFC Asian Cup qualification,P'yŏngyang,Korea DPR,False
38890,2018-03-27,Kyrgyzstan,India,2,1,AFC Asian Cup qualification,Bishkek,Kyrgyzstan,False
38892,2018-03-27,Lebanon,Malaysia,2,1,AFC Asian Cup qualification,Beirut,Lebanon,False
38894,2018-03-27,Maldives,Bhutan,7,0,AFC Asian Cup qualification,Malé,Maldives,False
38901,2018-03-27,Oman,Palestine,1,0,AFC Asian Cup qualification,Muscat,Oman,False
38903,2018-03-27,Philippines,Tajikistan,2,1,AFC Asian Cup qualification,Manila,Philippines,False
38912,2018-03-27,Taiwan,Singapore,1,0,AFC Asian Cup qualification,Taipei,Taiwan,False
38918,2018-03-27,Yemen,Nepal,2,1,AFC Asian Cup qualification,Doha,Qatar,True
38935,2018-05-27,Madagascar,Mozambique,2,1,COSAFA Cup,Polokwane,South Africa,True
38936,2018-05-27,Comoros,Seychelles,1,1,COSAFA Cup,Polokwane,South Africa,True
38947,2018-05-28,Malawi,Mauritius,0,1,COSAFA Cup,Polokwane,South Africa,True
38948,2018-05-28,Angola,Botswana,1,2,COSAFA Cup,Polokwane,South Africa,True
38955,2018-05-29,Madagascar,Seychelles,1,1,COSAFA Cup,Polokwane,South Africa,True
38956,2018-05-29,Comoros,Mozambique,0,3,COSAFA Cup,Polokwane,South Africa,True
38960,2018-05-30,Malawi,Botswana,1,1,COSAFA Cup,Polokwane,South Africa,True
38961,2018-05-30,Angola,Mauritius,1,0,COSAFA Cup,Polokwane,South Africa,True
38962,2018-05-30,Estonia,Lithuania,2,0,Baltic Cup,Rakvere,Estonia,False
38966,2018-05-31,Mozambique,Seychelles,2,1,COSAFA Cup,Polokwane,South Africa,True
38967,2018-05-31,Comoros,Madagascar,0,1,COSAFA Cup,Polokwane,South Africa,True
38976,2018-06-01,Botswana,Mauritius,6,0,COSAFA Cup,Polokwane,South Africa,True
38977,2018-06-01,Angola,Malawi,0,0,COSAFA Cup,Polokwane,South Africa,True
38990,2018-06-02,Zambia,Namibia,0,0,COSAFA Cup,Polokwane,South Africa,True
38991,2018-06-02,Lesotho,Swaziland,1,0,COSAFA Cup,Polokwane,South Africa,True
38992,2018-06-02,Latvia,Estonia,1,0,Baltic Cup,Riga,Latvia,False
39001,2018-06-03,South Africa,Madagascar,0,0,COSAFA Cup,Polokwane,South Africa,False
39002,2018-06-03,Zimbabwe,Botswana,1,1,COSAFA Cup,Polokwane,South Africa,True
39015,2018-06-05,South Africa,Namibia,4,1,COSAFA Cup,Polokwane,South Africa,False
39016,2018-06-05,Swaziland,Botswana,0,2,COSAFA Cup,Polokwane,South Africa,True
39021,2018-06-06,Zambia,Madagascar,1,0,COSAFA Cup,Polokwane,South Africa,True
39022,2018-06-06,Lesotho,Zimbabwe,0,0,COSAFA Cup,Polokwane,South Africa,True

In [16]:
world_cup

,Group,First match against,Second match against,Third match against
Team,,,,
Russia,A,Saudi Arabia,Egypt,Uruguay
Saudi Arabia,A,Russia,Uruguay,Egypt
Egypt,A,Uruguay,Russia,Saudi Arabia
Uruguay,A,Egypt,Saudi Arabia,Russia
Portugal,B,Spain,Morocco,Iran
Spain,B,Portugal,Iran,Morocco
Morocco,B,Iran,Portugal,Spain
Iran,B,Morocco,Spain,Portugal
France,C,Australia,Peru,Denmark
Australia,C,France,Denmark,Peru
Peru,C,Denmark,France,Australia
Denmark,C,Peru,Australia,France
Argentina,D,Iceland,Croatia,Nigeria
Iceland,D,Argentina,Nigeria,Croatia
Croatia,D,Nigeria,Argentina,Iceland
Nigeria,D,Croatia,Iceland,Argentina
Brazil,E,Switzerland,Costa Rica,Serbia
Switzerland,E,Brazil,Serbia,Costa Rica
Costa Rica,E,Serbia,Brazil,Switzerland
Serbia,E,Costa Rica,Switzerland,Brazil
Germany,F,Mexico,Sweden,Korea Republic
Mexico,F,Germany,Korea Republic,Sweden
Sweden,F,Korea Republic,Germany,Mexico
Korea Republic,F,Sweden,Mexico,Germany
Belgium,G,Panama,Tunisia,England
Panama,G,Belgium,England,Tunisia
Tunisia,G,England,Belgium,Panama
England,G,Tunisia,Panama,Belgium
Poland,H,Senegal,Colombia,Japan
Senegal,H,Poland,Japan,Colombia
Colombia,H,Japan,Poland,Senegal
Japan,H,Colombia,Senegal,Poland